In [3]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TimeSeriesSplit(max_train_size=None, n_splits=3)
TRAIN: [0 1 2] TEST: [3]
TRAIN: [0 1 2 3] TEST: [4]
TRAIN: [0 1 2 3 4] TEST: [5]

In [3]:
import pandas as pd
import os
import time
import patoolib
import gzip
import shutil
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from mpl_finance import candlestick_ohlc
import datetime as dt
from tqdm import tqdm_notebook
import pickle
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV

folder = "E:\\Pickles\\two_weeks_files"
with (open(os.path.join(folder,"EURGBP_two_weeks_files_EURGBP_Bars_20180304_EURGBP_Bars_20180318.pkl"), "rb")) as file:
    resampled_EURGBP = pickle.load(file)
resampled_EURGBP.head()

,Open,High,Low,Close,Max_20_per,Min_20_per,Max_30_per,Min_30_per,Max_40_per,Min_40_per,...,EMA_200_52_per_ago_%,EMA_200_53_per_ago_%,EMA_200_54_per_ago_%,EMA_200_55_per_ago_%,EMA_200_56_per_ago_%,EMA_200_57_per_ago_%,EMA_200_58_per_ago_%,EMA_200_59_per_ago_%,EMA_200_60_per_ago_%,Price_change_12_per_forward
DateTime_UTC,,,,,,,,,,,,,,,,,,,,,
2018-03-04 22:15:30,0.894825,0.894900,0.894625,0.894900,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2018-03-04 22:16:00,0.894900,0.894950,0.894875,0.894925,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2018-03-04 22:16:30,0.894925,0.894975,0.894850,0.894850,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2018-03-04 22:17:00,0.894850,0.894975,0.894825,0.894925,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2018-03-04 22:17:30,0.894925,0.894925,0.894750,0.894750,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [33]:
resampled_EURGBP.shape

(28500, 12262)

In [34]:
resampled_EURGBP.dtypes.sort_values()

Price_change_12_per_forward                      int64
Fast_Stoch_56_per_21_smoothing_55_per_ago_%    float64
Slow_Stoch_56_per_21_smoothing_55_per_ago_%    float64
Fast_Stoch_56_per_21_smoothing_56_per_ago_%    float64
Slow_Stoch_56_per_21_smoothing_56_per_ago_%    float64
                                                ...
BB_upper_band_90_per_57_per_ago_%              float64
BB_lower_band_90_per_57_per_ago_%              float64
BB_middle_band_90_per_58_per_ago_%             float64
BB_middle_band_90_per_55_per_ago_%             float64
Slow_Stoch_28_per_12_smoothing_55_per_ago_%    float64
Length: 12262, dtype: object

#### Missing Values

In [39]:
resampled_EURGBP.isna().sum().sort_values(ascending=False)[resampled_EURGBP.isna().sum().sort_values(ascending=False)>0]

Min_480_per_60_per_ago_%    539
Max_480_per_60_per_ago_%    539
Min_480_per_59_per_ago_%    538
Max_480_per_59_per_ago_%    538
Min_480_per_58_per_ago_%    537
                           ...
EMA_21_1_per_ago_%            1
EMA_11_1_per_ago_%            1
EMA_13_1_per_ago_%            1
EMA_20_1_per_ago_%            1
Open_1_per_ago_%              1
Length: 12244, dtype: int64

In [42]:
print(f"Lowest value in the entire df is: {resampled_EURGBP.min().min()}")

Lowest value in the entire df is: -1e+18

In [41]:
resampled_EURGBP.fillna(-999999999999999999, inplace=True)

#### Max Values

In [43]:
# Max values across df
resampled_EURGBP.max().sort_values(ascending=False)

Fast_Stoch_42_per_12_smoothing_8_per_ago_%         inf
Fast_Stoch_70_per_6_smoothing_20_per_ago_%         inf
Fast_Stoch_70_per_6_smoothing_18_per_ago_%         inf
Fast_Stoch_70_per_6_smoothing_17_per_ago_%         inf
Fast_Stoch_70_per_6_smoothing_16_per_ago_%         inf
                                                ...
EMA_150_1_per_ago_%                           0.001658
SMA_200_1_per_ago_%                           0.001596
BB_middle_band_200_per_1_per_ago_%            0.001591
EMA_200_1_per_ago_%                           0.001400
BB_middle_band_300_per_1_per_ago_%            0.001291
Length: 12262, dtype: float64

In [44]:
# Max values without np.inf
resampled_EURGBP.max()[resampled_EURGBP.max().sort_values(ascending=False)!=np.inf].sort_values(ascending=False)

Fast_Stoch_84_per_9_smoothing_51_per_ago_%    7.388718e+18
Fast_Stoch_84_per_9_smoothing_55_per_ago_%    7.124835e+18
Fast_Stoch_84_per_9_smoothing_52_per_ago_%    7.124835e+18
Fast_Stoch_84_per_9_smoothing_60_per_ago_%    7.124835e+18
Fast_Stoch_84_per_9_smoothing_50_per_ago_%    7.124835e+18
                                                  ...
EMA_150_1_per_ago_%                           1.658120e-03
SMA_200_1_per_ago_%                           1.596132e-03
BB_middle_band_200_per_1_per_ago_%            1.590741e-03
EMA_200_1_per_ago_%                           1.400287e-03
BB_middle_band_300_per_1_per_ago_%            1.290763e-03
Length: 10522, dtype: float64

In [45]:
# Imputing np.inf max values with the second largest value + 1000
inf_features = list(resampled_EURGBP.max()[resampled_EURGBP.max().sort_values(ascending=False)==np.inf].index)
for column in inf_features:
    largest_value = np.sort(resampled_EURGBP[column].unique())[-2]
    if largest_value != np.inf:
        resampled_EURGBP[column].replace(np.inf, largest_value+1000, inplace=True)
    else:
        print(f"second largest_value was found as np.inf for {column}")

In [257]:
resampled_EURGBP.min().sort_values(ascending=False)

EMA_200                                        8.908287e-01
EMA_150                                        8.908286e-01
EMA_100                                        8.908284e-01
EMA_50                                         8.908279e-01
EMA_40                                         8.908277e-01
                                                   ...
Fast_Stoch_56_per_21_smoothing_51_per_ago_%   -1.000000e+18
Slow_Stoch_56_per_21_smoothing_50_per_ago_%   -1.000000e+18
Fast_Stoch_56_per_21_smoothing_50_per_ago_%   -1.000000e+18
Slow_Stoch_56_per_21_smoothing_49_per_ago_%   -1.000000e+18
Slow_Stoch_28_per_12_smoothing_55_per_ago_%   -1.000000e+18
Length: 12262, dtype: float64

In [35]:
# Class proportions
resampled_EURGBP["Price_change_12_per_forward"].value_counts(normalize=True)

 0    0.825474
 1    0.094386
-1    0.080140
Name: Price_change_12_per_forward, dtype: float64

In [38]:
class_0 = resampled_EURGBP["Price_change_12_per_forward"].value_counts(normalize=True)[0]
class_1 = resampled_EURGBP["Price_change_12_per_forward"].value_counts(normalize=True)[1]
class_minus_1 = resampled_EURGBP["Price_change_12_per_forward"].value_counts(normalize=True)[-1]

weight_class_0 = 1
weight_class_1 = class_0/class_1
weight_class_minus_1 = class_0/class_minus_1

print("If dominant class (0) has got weight of 1 then:")
print(" ")
print("Weigh of class 1 ought to be:",weight_class_1)
print("Weight of class -1 ought to be:",weight_class_minus_1)

If dominant class (0) has got weight of 1 then:

Weigh of class 1 ought to be: 8.745724907063197
Weight of class -1 ought to be: 10.300350262697023

In [4]:
from sklearn.model_selection import TimeSeriesSplit

# Holdout set
X_holdout = resampled_EURGBP.loc[resampled_EURGBP.index.day.isin(resampled_EURGBP.index.day.unique()[-2::]),:].drop("Price_change_12_per_forward", axis="columns")
y_holdout = resampled_EURGBP.loc[resampled_EURGBP.index.day.isin(resampled_EURGBP.index.day.unique()[-2::]),"Price_change_12_per_forward"]

In [100]:
resampled_EURGBP

,Open,High,Low,Close,Max_20_per,Min_20_per,Max_30_per,Min_30_per,Max_40_per,Min_40_per,...,EMA_200_52_per_ago_%,EMA_200_53_per_ago_%,EMA_200_54_per_ago_%,EMA_200_55_per_ago_%,EMA_200_56_per_ago_%,EMA_200_57_per_ago_%,EMA_200_58_per_ago_%,EMA_200_59_per_ago_%,EMA_200_60_per_ago_%,Price_change_12_per_forward
DateTime_UTC,,,,,,,,,,,,,,,,,,,,,
2018-03-04 22:15:30,0.894825,0.894900,0.894625,0.894900,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,1
2018-03-04 22:16:00,0.894900,0.894950,0.894875,0.894925,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,0
2018-03-04 22:16:30,0.894925,0.894975,0.894850,0.894850,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,0
2018-03-04 22:17:00,0.894850,0.894975,0.894825,0.894925,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,1
2018-03-04 22:17:30,0.894925,0.894925,0.894750,0.894750,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-16 20:58:00,0.881200,0.881225,0.881175,0.881175,8.814250e-01,8.810500e-01,8.814250e-01,8.810250e-01,8.814250e-01,8.810250e-01,...,-9.263964e-03,-9.523779e-03,-9.784891e-03,-1.004731e-02,-1.029686e-02,-1.047676e-02,-1.062920e-02,-1.081077e-02,-1.099324e-02,0
2018-03-16 20:58:30,0.881175,0.881300,0.881150,0.881275,8.814250e-01,8.810500e-01,8.814250e-01,8.810250e-01,8.814250e-01,8.810250e-01,...,-9.090911e-03,-9.349434e-03,-9.609249e-03,-9.870361e-03,-1.013278e-02,-1.038233e-02,-1.056223e-02,-1.071467e-02,-1.089624e-02,0
2018-03-16 20:59:00,0.881275,0.881300,0.881175,0.881250,8.814250e-01,8.810500e-01,8.814250e-01,8.810250e-01,8.814250e-01,8.810250e-01,...,-8.946936e-03,-9.190066e-03,-9.448589e-03,-9.708403e-03,-9.969516e-03,-1.023193e-02,-1.048148e-02,-1.066138e-02,-1.081383e-02,0
2018-03-16 20:59:30,0.881250,0.881375,0.881225,0.881325,8.814250e-01,8.810500e-01,8.814250e-01,8.810250e-01,8.814250e-01,8.810250e-01,...,-8.761347e-03,-9.003269e-03,-9.246398e-03,-9.504921e-03,-9.764736e-03,-1.002585e-02,-1.028826e-02,-1.053781e-02,-1.071771e-02,0
2018-03-16 21:00:00,0.881325,0.881375,0.881275,0.881375,8.814250e-01,8.811250e-01,8.814250e-01,8.810250e-01,8.814250e-01,8.810250e-01,...,-8.534353e-03,-8.789180e-03,-9.031101e-03,-9.274231e-03,-9.532754e-03,-9.792568e-03,-1.005368e-02,-1.031610e-02,-1.056564e-02,0

In [10]:
tscv = TimeSeriesSplit(n_splits=3, max_train_size=None)

# initialize data
X = resampled_EURGBP.loc[resampled_EURGBP.index.day.isin(resampled_EURGBP.index.day.unique()[:-2]),:].drop("Price_change_12_per_forward", axis="columns")
y = resampled_EURGBP.loc[resampled_EURGBP.index.day.isin(resampled_EURGBP.index.day.unique()[:-2]),"Price_change_12_per_forward"]
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [   0    1    2 ... 5780 5781 5782] TEST: [ 5783  5784  5785 ... 11562 11563 11564]

KeyError: "None of [Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,\n            ...\n            5773, 5774, 5775, 5776, 5777, 5778, 5779, 5780, 5781, 5782],\n           dtype='int64', length=5783)] are in the [columns]"

In [4]:
def split(self, X, y=None, groups=None):
        """Generate indices to split data into training and test set.
        Parameters
        ----------
        X : array-like, shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.
        y : array-like, shape (n_samples,)
            The target variable for supervised learning problems.
        groups : array-like, with shape (n_samples,), optional
            Group labels for the samples used while splitting the dataset into
            train/test set.
        Yields
        ------
        train : ndarray
            The training set indices for that split.
        test : ndarray
            The testing set indices for that split.
        Notes
        -----
        Randomized CV splitters may return different results for each call of
        split. You can make the results identical by setting ``random_state``
        to an integer.
        """
#         X, y, groups = indexable(X, y, groups)
        indicies = np.arange(1000)
#         for train, test in X[0:500], X.iloc[501:]:
        yield indicies[0:500], indicies[500::]

In [ ]:
#     cat.fit(
#     X_train, y_train,
#     eval_set=(X_test, y_test),
#     verbose=False,
# #     logging_level='Verbose',  # you can uncomment this for text output
#     plot=True
# );

In [2]:
from catboost import CatBoost
import numpy as np
from sklearn.model_selection import ShuffleSplit

ss = ShuffleSplit(n_splits=3, test_size=0.25, random_state=0)

train_data = np.random.randint(1, 1000, size=(1000, 10))
train_labels = np.random.randint(2, size=(1000))

model = CatBoost(custom_loss=['Accuracy',"Precision","Recall"])

grid = {'learning_rate': [0.03, 0.1],
        'depth': [4, 6],
        'l2_leaf_reg': [5, 7]}

grid_search_result = model.grid_search(grid, 
                                       X=train_data, 
                                       y=train_labels,
                                       cv=split(train_data,3),
                                       plot=True)

TypeError: __init__() got an unexpected keyword argument 'custom_loss'

In [329]:
X.iloc[19274:19275,:]

,Open,High,Low,Close,Max_20_per,Min_20_per,Max_30_per,Min_30_per,Max_40_per,Min_40_per,...,EMA_200_51_per_ago_%,EMA_200_52_per_ago_%,EMA_200_53_per_ago_%,EMA_200_54_per_ago_%,EMA_200_55_per_ago_%,EMA_200_56_per_ago_%,EMA_200_57_per_ago_%,EMA_200_58_per_ago_%,EMA_200_59_per_ago_%,EMA_200_60_per_ago_%
DateTime_UTC,,,,,,,,,,,,,,,,,,,,,
2018-03-13 15:22:30,0.8867,0.886925,0.8867,0.886875,0.886875,0.8864,0.886875,0.886375,0.886875,0.8862,...,-0.001821,-0.002303,-0.002802,-0.003232,-0.003665,-0.004086,-0.004382,-0.004666,-0.004909,-0.005181

In [330]:
X.iloc[23128:23129,:]

,Open,High,Low,Close,Max_20_per,Min_20_per,Max_30_per,Min_30_per,Max_40_per,Min_40_per,...,EMA_200_51_per_ago_%,EMA_200_52_per_ago_%,EMA_200_53_per_ago_%,EMA_200_54_per_ago_%,EMA_200_55_per_ago_%,EMA_200_56_per_ago_%,EMA_200_57_per_ago_%,EMA_200_58_per_ago_%,EMA_200_59_per_ago_%,EMA_200_60_per_ago_%
DateTime_UTC,,,,,,,,,,,,,,,,,,,,,
2018-03-14 23:59:30,0.8858,0.8858,0.885775,0.885775,0.88585,0.88565,0.88585,0.88565,0.88585,0.88565,...,0.001726,0.001721,0.001688,0.001669,0.00165,0.001645,0.001697,0.001762,0.001814,0.001895

In [142]:
X.shape

(23129, 12261)

In [338]:
for train_index, test_index in n(X,3):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

[    0     1     2 ... 23126 23127 23128]
23129
4
1
TRAIN: [    0     1     2 ... 11562 11563 11564] TEST: [11565 11566 11567 ... 15417 15418 15419]
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-08 23:33:00', '2018-03-08 23:33:30',
               '2018-03-08 23:34:00', '2018-03-08 23:34:30',
               '2018-03-08 23:35:00', '2018-03-08 23:35:30',
               '2018-03-08 23:36:00', '2018-03-08 23:36:30',
               '2018-03-08 23:37:00', '2018-03-08 23:37:30'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=11565, freq=None)
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-08 23:33:00', '2018-03-08 23:33:30',
               '2018-03-08 23:34:00', '2018-03-08 23:34:30',
               '2018-03-08 23:35:00', '2018-03-08 23:35:30',
               '2018-03-08 23:36:00', '2018-03-08 23:36:30',
               '2018-03-08 23:37:00', '2018-03-08 23:37:30'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=11565, freq=None)
TRAIN: [    0     1     2 ... 15417 15418 15419] TEST: [15420 15421 15422 ... 19272 19273 19274]
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-12 06:55:30', '2018-03-12 06:56:00',
               '2018-03-12 06:56:30', '2018-03-12 06:57:00',
               '2018-03-12 06:57:30', '2018-03-12 06:58:00',
               '2018-03-12 06:58:30', '2018-03-12 06:59:00',
               '2018-03-12 06:59:30', '2018-03-12 07:00:00'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=15420, freq=None)
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-12 06:55:30', '2018-03-12 06:56:00',
               '2018-03-12 06:56:30', '2018-03-12 06:57:00',
               '2018-03-12 06:57:30', '2018-03-12 06:58:00',
               '2018-03-12 06:58:30', '2018-03-12 06:59:00',
               '2018-03-12 06:59:30', '2018-03-12 07:00:00'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=15420, freq=None)
TRAIN: [    0     1     2 ... 19272 19273 19274] TEST: [19275 19276 19277 ... 23126 23127 23128]
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-13 15:18:00', '2018-03-13 15:18:30',
               '2018-03-13 15:19:00', '2018-03-13 15:19:30',
               '2018-03-13 15:20:00', '2018-03-13 15:20:30',
               '2018-03-13 15:21:00', '2018-03-13 15:21:30',
               '2018-03-13 15:22:00', '2018-03-13 15:22:30'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=19275, freq=None)
DatetimeIndex(['2018-03-04 22:15:30', '2018-03-04 22:16:00',
               '2018-03-04 22:16:30', '2018-03-04 22:17:00',
               '2018-03-04 22:17:30', '2018-03-04 22:18:00',
               '2018-03-04 22:18:30', '2018-03-04 22:19:00',
               '2018-03-04 22:19:30', '2018-03-04 22:20:00',
               ...
               '2018-03-13 15:18:00', '2018-03-13 15:18:30',
               '2018-03-13 15:19:00', '2018-03-13 15:19:30',
               '2018-03-13 15:20:00', '2018-03-13 15:20:30',
               '2018-03-13 15:21:00', '2018-03-13 15:21:30',
               '2018-03-13 15:22:00', '2018-03-13 15:22:30'],
              dtype='datetime64[ns]', name='DateTime_UTC', length=19275, freq=None)

In [409]:
for train_index, test_index in split(X,3):
    print("TRAIN:", train_index, "TEST:", test_index)

[    0     1     2 ... 23126 23127 23128]
23129
4
1
TRAIN: [    0     1     2 ... 11562 11563 11564] TEST: [11565 11566 11567 ... 15417 15418 15419]
TRAIN: [    0     1     2 ... 15417 15418 15419] TEST: [15420 15421 15422 ... 19272 19273 19274]
TRAIN: [    0     1     2 ... 19272 19273 19274] TEST: [19275 19276 19277 ... 23126 23127 23128]

In [5]:
def split(X, splits, max_train_size=None):
#     X, y, groups = indexable(X, y, groups)
    n_samples = X.shape[0]
    n_splits = splits
    n_folds = n_splits + 1
    if n_folds > n_samples:
        raise ValueError(
            ("Cannot have number of folds ={0} greater"
             " than the number of samples: {1}.").format(n_folds,
                                                         n_samples))
    indices = np.arange(n_samples)
    print(indices)
    test_size = (n_samples // n_folds)
    print(n_samples)
    print(n_folds)
    print(n_samples % n_folds)
    test_starts = range(test_size*2 + n_samples % n_folds,
                        n_samples, round(test_size/1.5))
    for test_start in test_starts:
        if max_train_size and max_train_size < test_start:
            pass
#             yield (indices[test_start*2 - max_train_size:test_start*2],
#                    indices[test_start*2:test_start + test_size])
        else:
            yield (indices[:test_start],
                   indices[test_start:test_start + round(test_size/1.5)])