<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Hands on with SQL

### Download the flights dataset

https://www.dropbox.com/s/a2wax843eniq12g/flights.db?dl=1

This is a dataset of airlines, airports, and routes.

This is in SQLite format; a lightweight SQL library, where your entire database is a single file.

We can interact with SQLite using Python!

In [2]:
import sqlite3

We will also use `pandas` to run our SQL queries and display results. More on `pandas` later...

In [3]:
import pandas as pd

Open your database

In [4]:
db = sqlite3.connect('flights1.db')

The general form of a SQL query is:

```sql

SELECT
    <column(s)>
FROM
    <table(s)>
WHERE
    <condition(s)>
    
```

Unlike Python, indentation does **not** matter, it's just for readability.

- to select all columns, use `SELECT *`
- to select all rows, omit the `WHERE` part

Let's select all rows and columns from the airports table:

In [7]:
pd.read_sql("""
    SELECT
        *
    FROM
        airports
    """, con=db).head(5)

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
1,1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
2,2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
3,3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
4,4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby

Now only a few columns:

In [10]:
pd.read_sql("""
    SELECT
        name,
        timezone,
        city,
        code
    FROM
        airports
    """, con=db)

,name,timezone,city,code
0,Goroka,Pacific/Port_Moresby,Goroka,GKA
1,Madang,Pacific/Port_Moresby,Madang,MAG
2,Mount Hagen,Pacific/Port_Moresby,Mount Hagen,HGU
3,Nadzab,Pacific/Port_Moresby,Nadzab,LAE
4,Port Moresby Jacksons Intl,Pacific/Port_Moresby,Port Moresby,POM
5,Wewak Intl,Pacific/Port_Moresby,Wewak,WWK
6,Narsarsuaq,America/Godthab,Narssarssuaq,UAK
7,Nuuk,America/Godthab,Godthaab,GOH
8,Sondre Stromfjord,America/Godthab,Sondrestrom,SFJ
9,Thule Air Base,America/Thule,Thule,THU
10,Akureyri,Atlantic/Reykjavik,Akureyri,AEY
11,Egilsstadir,Atlantic/Reykjavik,Egilsstadir,EGS
12,Hornafjordur,Atlantic/Reykjavik,Hofn,HFN
13,Husavik,Atlantic/Reykjavik,Husavik,HZK
14,Isafjordur,Atlantic/Reykjavik,Isafjordur,IFJ
15,Keflavik International Airport,Atlantic/Reykjavik,Keflavik,KEF
16,Patreksfjordur,Atlantic/Reykjavik,Patreksfjordur,PFJ
17,Reykjavik,Atlantic/Reykjavik,Reykjavik,RKV
18,Siglufjordur,Atlantic/Reykjavik,Siglufjordur,SIJ
19,Vestmannaeyjar,Atlantic/Reykjavik,Vestmannaeyjar,VEY
20,Sault Ste Marie,America/Toronto,Sault Sainte Marie,YAM
21,Winnipeg St Andrews,America/Winnipeg,Winnipeg,YAV
22,Shearwater,America/Halifax,Halifax,YAW
23,St Anthony,America/St_Johns,St. Anthony,YAY
24,Tofino,America/Vancouver,Tofino,YAZ
25,Kugaaruk,America/Edmonton,Pelly Bay,YBB
26,Baie Comeau,America/Toronto,Baie Comeau,YBC
27,Bagotville,America/Toronto,Bagotville,YBG
28,Baker Lake,America/Winnipeg,Baker Lake,YBK
29,Campbell River,America/Vancouver,Campbell River,YBL
...,...,...,...,...
8077,Port of Seattle,America/Los_Angeles,Seattle,None
8078,Ferry Terminal,America/Anchorage,Whittier,None
8079,Ferry Terminal,America/Anchorage,Valdez,None
8080,Gare Routiere,Indian/Reunion,Saint-Louis,None
8081,Bus Stop,Indian/Reunion,La Riviere,None
8082,Bus Stop,Indian/Reunion,Cilaos,None
8083,Bus Stop,Indian/Reunion,Hell-Bourg,None
8084,Bus Stop,Indian/Reunion,Salazie,None
8085,Gare,Indian/Reunion,St Andre,None
8086,L'Ocean Bus Terminal,Indian/Reunion,Saint Denis,None
8087,Gare Routiere,Indian/Reunion,Saint Pierre,None
8088,Baie Ste Anne,Indian/Mahe,Praslin,None
8089,La Passe,Indian/Mahe,La Digue,None
8090,Ferry Dock,America/Los_Angeles,Bainbridge Island,None
8091,Bus,Asia/Phnom_Penh,Phnom Penh,None
8092,Bus,Asia/Phnom_Penh,Siem Reap,None
8093,Bus,Asia/Phnom_Penh,Sihanoukville,None
8094,Bus,Asia/Phnom_Penh,Kampot,None
8095,Bus,Asia/Phnom_Penh,Kep,None
8096,Main Station,Asia/Taipei,Taipei,None
8097,Prominent Hill,Australia/Adelaide,Prominent Hill,PXH
8098,Chatsworth Station,America/Los_Angeles,Chatsworth,CWT
8099,Algerciras Port,Europe/Madrid,Algerciras,None
8100,Ganges Water Aerodrome,America/Vancouver,Ganges,YGG
8101,Pender Harbour Water Aerodrome,America/Vancouver,Pender Harbour,YPT
8102,Mansons Landing Water Aerodrome,America/Vancouver,Mansons Landing,YMU
8103,Port McNeill Airport,America/Vancouver,Port McNeill,YMP
8104,Sullivan Bay Water Aerodrome,America/Vancouver,Sullivan Bay,YTG
8105,Deer Harbor Seaplane,America/Los_Angeles,Deer Harbor,DHB
8106,San Diego Old Town Transit Center,America/Los_Angeles,San Diego,OLT

Or filter some rows.

`WHERE` clauses can contain boolean combinations like `AND` and `OR`

In [9]:
pd.read_sql("""
    SELECT
        name
    FROM
        airports
    WHERE
        timezone = 'Europe/Madrid'
    """, con=db)

                           name
0                       Melilla
1                      Albacete
2                      Alicante
3                       Almeria
4                      Asturias
5                       Cordoba
6                        Bilbao
7                     Barcelona
8              Talavera La Real
9                      A Coruna
10                      Armilla
11                       Girona
12                      Granada
13                       Getafe
14                        Ibiza
15                        Jerez
16            Murcia San Javier
17                      Barajas
18                       Malaga
19                      Menorca
20                     Moron Ab
21                        Ocana
22                     Pamplona
23                 Alcantarilla
24                         Reus
25                      Rota Ns
26                    Salamanca
27                    Son Bonet
28            Palma De Mallorca
29                     San Luis
..                          ...
44    Logroño-Agoncillo Airport
45               Ceuta Heliport
46                Ronda Airport
47                        Ronda
48               Burgos Airport
49                 Leon Airport
50      Lleida-Alguaire Airport
51      Huesca-Pirineos Airport
52  Ciudad Real Central Airport
53                  La Cerdanya
54    Barcelona Cruise Terminal
55       Malaga Cruise Terminal
56         Vigo Cruise Terminal
57        Cadiz Cruise Terminal
58                       Tarifa
59           Algeciras Heliport
60           Algeciras Heliport
61        Fuentemilanos Airport
62                  Santa Justa
63              Cordoba Station
64              Granada Station
65                       Atocha
66       Toledo Railway Station
67            Chamartin Station
68                       Abando
69                     Aeroport
70            Passeig de Gracia
71                        Sants
72              Railway Station
73              Algerciras Port

[74 rows x 1 columns]

You can change the ordering using `ORDER BY`.

You can order ascending with `ORDER BY ASC` (the default) or `ORDER BY DESC`.

In [12]:
# pd.read_sql("""
#     SELECT
#         name
#     FROM
#         airports
#     ORDER BY
#         name
#     """, con=db)
pd.read_sql("""
    SELECT
        name
    FROM
        airports
    ORDER BY
        name desc
    """, con=db)

                                     name
0                          Žilina Airport
1          Łódź Władysław Reymont Airport
2                       Östersund Airport
3                    Île des Pins Airport
4                       Île d'Yeu Airport
5           Ängelholm-Helsingborg Airport
6                              \\'t Harde
7                   Zyryanka West Airport
8                            Zweibruecken
9                             Zweibrucken
10                             Zvishavane
11                              Zvartnots
12                              Zutendaal
13                                 Zurich
14                                 Zurich
15                        Zuoying Station
16                     Zumbi Dos Palmares
17                   Zorg en Hoop Airport
18                                    Zoo
19                              Zonguldak
20          Zona da Mata Regional Airport
21                                Zoersel
22                       Znamenka airport
23                           Ziyaraifushi
24                                  Zirku
25                                 Zinder
26                             Ziguinchor
27                               Zia Intl
28                               Zhytomyr
29                          Zhuliany Intl
...                                   ...
8077              Abraham Lincoln Capital
8078                Abraham Gonzalez Intl
8079                               Abqaiq
8080                         Abilene Rgnl
8081  Abidjan Felix Houphouet Boigny Intl
8082                                 Abha
8083            Aberdeen Regional Airport
8084             Aberdeen Railway Station
8085                     Aberdeen Harbour
8086                Abemama Atoll Airport
8087                      Abel Santamaria
8088                               Abeche
8089                  Abdul Rachman Saleh
8090                           Abbotsford
8091                            Abbeville
8092                               Abando
8093                               Abakan
8094                Abaiang Atoll Airport
8095                               Abadan
8096                              Aasiaat
8097                                 Aars
8098                               Aarhus
8099           Aalen Heidenheim Elchingen
8100                              Aalborg
8101                           Aachen HBF
8102                                  Aaa
8103                                AYaou
8104                             A Coruna
8105                                A 511
8106                           7 Novembre

[8107 rows x 1 columns]

## Aggregation

You can **summarise** the dataset with functions like:

- count
- sum
- avg
- min/max

depending on the data type of the column (you can't "average" text!)

In [11]:
pd.read_sql("""
    SELECT
        AVG(latitude),
        AVG(longitude)
    FROM
        airports
    """, con=db)

   AVG(latitude)  AVG(longitude)
0       26.81772       -3.921969

To calculate these metrics for smaller groups, you can **group** rows that are share a value in one or more columns.

In [14]:
pd.read_sql("""
    SELECT
        timezone,
        COUNT(name) 
    FROM
        airports
    GROUP BY
        timezone
    """, con=db)

                 timezone  COUNT(name)
0          Africa/Abidjan            7
1            Africa/Accra            6
2      Africa/Addis_Ababa           31
3          Africa/Algiers           44
4           Africa/Asmera            4
5           Africa/Bamako            8
6           Africa/Bangui            3
7           Africa/Banjul            1
8           Africa/Bissau            2
9         Africa/Blantyre            8
10     Africa/Brazzaville            5
11       Africa/Bujumbura            1
12           Africa/Cairo           21
13      Africa/Casablanca           22
14         Africa/Conakry            6
15           Africa/Dakar            9
16   Africa/Dar_es_Salaam           28
17        Africa/Djibouti            3
18          Africa/Douala           10
19        Africa/El_Aaiun            3
20        Africa/Freetown            8
21        Africa/Gaborone           25
22          Africa/Harare           16
23    Africa/Johannesburg          104
24            Africa/Juba            7
25         Africa/Kampala            9
26        Africa/Khartoum           14
27          Africa/Kigali            4
28        Africa/Kinshasa           18
29           Africa/Lagos           27
..                    ...          ...
264     Pacific/Enderbury            1
265          Pacific/Fiji           17
266      Pacific/Funafuti            1
267     Pacific/Galapagos            3
268       Pacific/Gambier            1
269   Pacific/Guadalcanal           26
270          Pacific/Guam            2
271      Pacific/Honolulu           25
272      Pacific/Johnston            1
273        Pacific/Kosrae            1
274        Pacific/Majuro           32
275     Pacific/Marquesas            4
276        Pacific/Midway            1
277         Pacific/Nauru            1
278          Pacific/Niue            1
279       Pacific/Norfolk            1
280        Pacific/Noumea           11
281     Pacific/Pago_Pago            3
282         Pacific/Palau            3
283        Pacific/Ponape            1
284  Pacific/Port_Moresby           57
285     Pacific/Rarotonga            8
286        Pacific/Saipan            3
287        Pacific/Tahiti           25
288        Pacific/Tarawa            8
289     Pacific/Tongatapu            6
290          Pacific/Truk            3
291          Pacific/Wake            1
292        Pacific/Wallis            2
293                    \N           92

[294 rows x 2 columns]

# Joining

First let's look at airline **routes**. We can select just a few rows with `LIMIT`:

In [13]:
#limit is like head - we select only a number of rows to print
pd.read_sql("""
    SELECT
        *
    FROM
        routes
    LIMIT
        10
    """, con=db)

,index,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
0,0,2B,410,AER,2965,KZN,2990,None,0,CR2
1,1,2B,410,ASF,2966,KZN,2990,None,0,CR2
2,2,2B,410,ASF,2966,MRV,2962,None,0,CR2
3,3,2B,410,CEK,2968,KZN,2990,None,0,CR2
4,4,2B,410,CEK,2968,OVB,4078,None,0,CR2
5,5,2B,410,DME,4029,KZN,2990,None,0,CR2
6,6,2B,410,DME,4029,NBC,6969,None,0,CR2
7,7,2B,410,DME,4029,TGK,\N,None,0,CR2
8,8,2B,410,DME,4029,UUA,6160,None,0,CR2
9,9,2B,410,EGO,6156,KGD,2952,None,0,CR2

`source_id` and `dest_id` both relate to the `airports` table

What kind of keys are they?

Now what if we wanted to find out which airports those IDs relate to?

To join tables together, you need to specify which columns match.

```sql

SELECT
    <column(s)>
FROM
    <table_1>
    JOIN <table_2> ON <condition(s)>

```

In [14]:
pd.read_sql("""
    SELECT
        routes.[index],
        routes.source_id,
        airports.name AS source_airport
    FROM
        routes
        JOIN airports ON routes.source_id = airports.id
""", con=db)

       index source_id                  source_airport
0          0      2965                           Sochi
1          1      2966                       Astrakhan
2          2      2966                       Astrakhan
3          3      2968                       Balandino
4          4      2968                       Balandino
5          5      4029                      Domododevo
6          6      4029                      Domododevo
7          7      4029                      Domododevo
8          8      4029                      Domododevo
9          9      6156  Belgorod International Airport
10        10      6156  Belgorod International Airport
11        11      2922                   Heydar Aliyev
12        12      2952                       Khrabrovo
13        13      2990                           Kazan
14        14      2990                           Kazan
15        15      2990                           Kazan
16        16      2990                           Kazan
17        17      2990                           Kazan
18        18      2990                           Kazan
19        19      2990                           Kazan
20        20      2948                         Pulkovo
21        21      2948                         Pulkovo
22        22      2948                         Pulkovo
23        23      2962                Mineralnyye Vody
24        24      6969                       Begishevo
25        25      6969                       Begishevo
26        26      6969                       Begishevo
27        27      6969                       Begishevo
28        28      2972                  Nizhnevartovsk
29        29      2972                  Nizhnevartovsk
...      ...       ...                             ...
67394  67633      3361                     Sydney Intl
67395  67634      3361                     Sydney Intl
67396  67635      3361                     Sydney Intl
67397  67636      3361                     Sydney Intl
67398  67637      3361                     Sydney Intl
67399  67638      3361                     Sydney Intl
67400  67639      3361                     Sydney Intl
67401  67640      3361                     Sydney Intl
67402  67641      3361                     Sydney Intl
67403  67642      3361                     Sydney Intl
67404  67643      3361                     Sydney Intl
67405  67644      3361                     Sydney Intl
67406  67645      3361                     Sydney Intl
67407  67646      3361                     Sydney Intl
67408  67647      3361                     Sydney Intl
67409  67648      3361                     Sydney Intl
67410  67649      3361                     Sydney Intl
67411  67650      6794                   Taree Airport
67412  67651      6794                   Taree Airport
67413  67652      3330                      Townsville
67414  67653      3330                      Townsville
67415  67654      3363                     Wagga Wagga
67416  67655      3363                     Wagga Wagga
67417  67656      6337                  Winton Airport
67418  67657      6337                  Winton Airport
67419  67658      6334                 Whyalla Airport
67420  67659      4029                      Domododevo
67421  67660      2912                           Manas
67422  67661      2912                           Manas
67423  67662      2913                             Osh

[67424 rows x 3 columns]

It's a good idea to put the table name before each column when you join, so you know what came from where.

Notice you can rename columns in the output with `AS`.

You can do multiple `JOIN`s and rename tables with `AS`:

In [15]:
pd.read_sql("""
    SELECT
        routes.[index],
        routes.source_id,
        origin.name AS source_airport,
        routes.dest_id,
        destination.name AS destination_airport
    FROM
        routes
        JOIN airports AS origin ON routes.source_id = origin.id
        JOIN airports AS destination ON routes.dest_id = destination.id
""", con=db)

,index,source_id,source_airport,dest_id,destination_airport
0,0,2965,Sochi,2990,Kazan
1,1,2966,Astrakhan,2990,Kazan
2,2,2966,Astrakhan,2962,Mineralnyye Vody
3,3,2968,Balandino,2990,Kazan
4,4,2968,Balandino,4078,Tolmachevo
5,5,4029,Domododevo,2990,Kazan
6,6,4029,Domododevo,6969,Begishevo
7,8,4029,Domododevo,6160,Bugulma Airport
8,9,6156,Belgorod International Airport,2952,Khrabrovo
9,10,6156,Belgorod International Airport,2990,Kazan
10,11,2922,Heydar Aliyev,6969,Begishevo
11,12,2952,Khrabrovo,6156,Belgorod International Airport
12,13,2990,Kazan,2965,Sochi
13,14,2990,Kazan,2966,Astrakhan
14,15,2990,Kazan,2968,Balandino
15,16,2990,Kazan,4029,Domododevo
16,17,2990,Kazan,6156,Belgorod International Airport
17,18,2990,Kazan,2948,Pulkovo
18,19,2990,Kazan,2975,Koltsovo
19,20,2948,Pulkovo,2990,Kazan
20,21,2948,Pulkovo,6969,Begishevo
21,22,2948,Pulkovo,6160,Bugulma Airport
22,23,2962,Mineralnyye Vody,2966,Astrakhan
23,24,6969,Begishevo,4029,Domododevo
24,25,6969,Begishevo,2922,Heydar Aliyev
25,26,6969,Begishevo,2948,Pulkovo
26,27,6969,Begishevo,2975,Koltsovo
27,28,2972,Nizhnevartovsk,2975,Koltsovo
28,29,2972,Nizhnevartovsk,6160,Bugulma Airport
29,30,4364,Novyi Urengoy,2975,Koltsovo
...,...,...,...,...,...
67172,67633,3361,Sydney Intl,3333,Albury
67173,67634,3361,Sydney Intl,4062,Armidale
67174,67635,3361,Sydney Intl,6241,Broken Hill Airport
67175,67636,3361,Sydney Intl,6249,Bathurst Airport
67176,67637,3361,Sydney Intl,4291,Ballina Byron Gateway
67177,67638,3361,Sydney Intl,3358,Dubbo
67178,67639,3361,Sydney Intl,6271,Griffith Airport
67179,67640,3361,Sydney Intl,6287,Lismore Airport
67180,67641,3361,Sydney Intl,6294,Merimbula Airport
67181,67642,3361,Sydney Intl,6298,Mildura Airport
67182,67643,3361,Sydney Intl,6302,Moruya Airport
67183,67644,3361,Sydney Intl,6307,Narrandera Airport
67184,67645,3361,Sydney Intl,4320,Newcastle Airport
67185,67646,3361,Sydney Intl,6793,Orange Airport
67186,67647,3361,Sydney Intl,6317,Parkes Airport
67187,67648,3361,Sydney Intl,6794,Taree Airport
67188,67649,3361,Sydney Intl,3363,Wagga Wagga
67189,67650,6794,Taree Airport,6792,Grafton Airport
67190,67651,6794,Taree Airport,3361,Sydney Intl
67191,67652,3330,Townsville,3324,Mount Isa
67192,67653,3330,Townsville,6337,Winton Airport
67193,67654,3363,Wagga Wagga,3339,Melbourne Intl
67194,67655,3363,Wagga Wagga,3361,Sydney Intl
67195,67656,6337,Winton Airport,6289,Longreach Airport
67196,67657,6337,Winton Airport,3330,Townsville
67197,67658,6334,Whyalla Airport,3341,Adelaide Intl
67198,67659,4029,Domododevo,2912,Manas
67199,67660,2912,Manas,4029,Domododevo
67200,67661,2912,Manas,2913,Osh
67201,67662,2913,Osh,2912,Manas

# Types of JOIN

![](assets/db/joins.png)